name: Fastlane 2 iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.4"

      - name: Install dependencies
        run: flutter pub get

      # ✅ Step B6: Install signing credentials
      - name: Decode signing certificate and profile
        run: |
          mkdir -p ~/certs
          echo "$P12_BASE64" | base64 --decode > ~/certs/cert.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/certs/profile.mobileprovision
          echo "$PROVISIONING_PROFILE_EXT_BASE64" | base64 --decode > ~/certs/ext_profile.mobileprovision
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          PROVISIONING_PROFILE_EXT_BASE64: ${{ secrets.PROVISIONING_PROFILE_EXT_BASE64 }}

      - name: Install provisioning profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ~/certs/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          cp ~/certs/ext_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      
      - name: Debug secret lengths
        run: |
          echo "Length of P12_BASE64: ${#P12_BASE64}"
          echo "Length of PROVISIONING_PROFILE_BASE64: ${#PROVISIONING_PROFILE_BASE64}"
          echo "Length of PROVISIONING_PROFILE_EXT_BASE64: ${#PROVISIONING_PROFILE_EXT_BASE64}"
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          PROVISIONING_PROFILE_EXT_BASE64: ${{ secrets.PROVISIONING_PROFILE_EXT_BASE64 }}


      - name: Debug certificate file
        run: |
          ls -lh ~/certs
          file ~/certs/cert.p12
          echo "Password length: ${#P12_PASSWORD}"
          echo "Trying OpenSSL..."
          openssl pkcs12 -in ~/certs/cert.p12 -nokeys -info -passin "pass:${P12_PASSWORD}" || true
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

          
      - name: Install certificate
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import ~/certs/cert.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}


      

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: Build iOS archive
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=CW3CBV8SF4 \
            PROVISIONING_PROFILE_SPECIFIER="match AppStore com.necasoft.mcbslive" \
            OTHER_CODE_SIGN_FLAGS="--keychain build.keychain" \
            archive


            
      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath ios/build/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath ios/build/ipa

      - name: Upload IPA as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: ios/build/ipa/Runner.ipa

      - name: Upload .app as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app
